# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/acy/develop/rhea

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/acy/develop/rhea

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/acy/develop/rhea/CMakeFiles /home/acy/develop/rhea/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/acy/develop/rhea/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named rhea-diary

# Build rule for target.
rhea-diary: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rhea-diary
.PHONY : rhea-diary

# fast build rule for target.
rhea-diary/fast:
	$(MAKE) -f CMakeFiles/rhea-diary.dir/build.make CMakeFiles/rhea-diary.dir/build
.PHONY : rhea-diary/fast

#=============================================================================
# Target rules for targets named metis2xml

# Build rule for target.
metis2xml: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 metis2xml
.PHONY : metis2xml

# fast build rule for target.
metis2xml/fast:
	$(MAKE) -f CMakeFiles/metis2xml.dir/build.make CMakeFiles/metis2xml.dir/build
.PHONY : metis2xml/fast

#=============================================================================
# Target rules for targets named rhea-rel

# Build rule for target.
rhea-rel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rhea-rel
.PHONY : rhea-rel

# fast build rule for target.
rhea-rel/fast:
	$(MAKE) -f CMakeFiles/rhea-rel.dir/build.make CMakeFiles/rhea-rel.dir/build
.PHONY : rhea-rel/fast

#=============================================================================
# Target rules for targets named rhea-content

# Build rule for target.
rhea-content: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 rhea-content
.PHONY : rhea-content

# fast build rule for target.
rhea-content/fast:
	$(MAKE) -f CMakeFiles/rhea-content.dir/build.make CMakeFiles/rhea-content.dir/build
.PHONY : rhea-content/fast

diary.o: diary.cpp.o

.PHONY : diary.o

# target to build an object file
diary.cpp.o:
	$(MAKE) -f CMakeFiles/rhea-diary.dir/build.make CMakeFiles/rhea-diary.dir/diary.cpp.o
.PHONY : diary.cpp.o

diary.i: diary.cpp.i

.PHONY : diary.i

# target to preprocess a source file
diary.cpp.i:
	$(MAKE) -f CMakeFiles/rhea-diary.dir/build.make CMakeFiles/rhea-diary.dir/diary.cpp.i
.PHONY : diary.cpp.i

diary.s: diary.cpp.s

.PHONY : diary.s

# target to generate assembly for a file
diary.cpp.s:
	$(MAKE) -f CMakeFiles/rhea-diary.dir/build.make CMakeFiles/rhea-diary.dir/diary.cpp.s
.PHONY : diary.cpp.s

diary_main.o: diary_main.cpp.o

.PHONY : diary_main.o

# target to build an object file
diary_main.cpp.o:
	$(MAKE) -f CMakeFiles/rhea-diary.dir/build.make CMakeFiles/rhea-diary.dir/diary_main.cpp.o
.PHONY : diary_main.cpp.o

diary_main.i: diary_main.cpp.i

.PHONY : diary_main.i

# target to preprocess a source file
diary_main.cpp.i:
	$(MAKE) -f CMakeFiles/rhea-diary.dir/build.make CMakeFiles/rhea-diary.dir/diary_main.cpp.i
.PHONY : diary_main.cpp.i

diary_main.s: diary_main.cpp.s

.PHONY : diary_main.s

# target to generate assembly for a file
diary_main.cpp.s:
	$(MAKE) -f CMakeFiles/rhea-diary.dir/build.make CMakeFiles/rhea-diary.dir/diary_main.cpp.s
.PHONY : diary_main.cpp.s

m2x_main.o: m2x_main.cpp.o

.PHONY : m2x_main.o

# target to build an object file
m2x_main.cpp.o:
	$(MAKE) -f CMakeFiles/metis2xml.dir/build.make CMakeFiles/metis2xml.dir/m2x_main.cpp.o
.PHONY : m2x_main.cpp.o

m2x_main.i: m2x_main.cpp.i

.PHONY : m2x_main.i

# target to preprocess a source file
m2x_main.cpp.i:
	$(MAKE) -f CMakeFiles/metis2xml.dir/build.make CMakeFiles/metis2xml.dir/m2x_main.cpp.i
.PHONY : m2x_main.cpp.i

m2x_main.s: m2x_main.cpp.s

.PHONY : m2x_main.s

# target to generate assembly for a file
m2x_main.cpp.s:
	$(MAKE) -f CMakeFiles/metis2xml.dir/build.make CMakeFiles/metis2xml.dir/m2x_main.cpp.s
.PHONY : m2x_main.cpp.s

metis2xml.o: metis2xml.cpp.o

.PHONY : metis2xml.o

# target to build an object file
metis2xml.cpp.o:
	$(MAKE) -f CMakeFiles/metis2xml.dir/build.make CMakeFiles/metis2xml.dir/metis2xml.cpp.o
.PHONY : metis2xml.cpp.o

metis2xml.i: metis2xml.cpp.i

.PHONY : metis2xml.i

# target to preprocess a source file
metis2xml.cpp.i:
	$(MAKE) -f CMakeFiles/metis2xml.dir/build.make CMakeFiles/metis2xml.dir/metis2xml.cpp.i
.PHONY : metis2xml.cpp.i

metis2xml.s: metis2xml.cpp.s

.PHONY : metis2xml.s

# target to generate assembly for a file
metis2xml.cpp.s:
	$(MAKE) -f CMakeFiles/metis2xml.dir/build.make CMakeFiles/metis2xml.dir/metis2xml.cpp.s
.PHONY : metis2xml.cpp.s

refer.o: refer.cpp.o

.PHONY : refer.o

# target to build an object file
refer.cpp.o:
	$(MAKE) -f CMakeFiles/rhea-rel.dir/build.make CMakeFiles/rhea-rel.dir/refer.cpp.o
.PHONY : refer.cpp.o

refer.i: refer.cpp.i

.PHONY : refer.i

# target to preprocess a source file
refer.cpp.i:
	$(MAKE) -f CMakeFiles/rhea-rel.dir/build.make CMakeFiles/rhea-rel.dir/refer.cpp.i
.PHONY : refer.cpp.i

refer.s: refer.cpp.s

.PHONY : refer.s

# target to generate assembly for a file
refer.cpp.s:
	$(MAKE) -f CMakeFiles/rhea-rel.dir/build.make CMakeFiles/rhea-rel.dir/refer.cpp.s
.PHONY : refer.cpp.s

rel-ref.o: rel-ref.cpp.o

.PHONY : rel-ref.o

# target to build an object file
rel-ref.cpp.o:
	$(MAKE) -f CMakeFiles/rhea-content.dir/build.make CMakeFiles/rhea-content.dir/rel-ref.cpp.o
.PHONY : rel-ref.cpp.o

rel-ref.i: rel-ref.cpp.i

.PHONY : rel-ref.i

# target to preprocess a source file
rel-ref.cpp.i:
	$(MAKE) -f CMakeFiles/rhea-content.dir/build.make CMakeFiles/rhea-content.dir/rel-ref.cpp.i
.PHONY : rel-ref.cpp.i

rel-ref.s: rel-ref.cpp.s

.PHONY : rel-ref.s

# target to generate assembly for a file
rel-ref.cpp.s:
	$(MAKE) -f CMakeFiles/rhea-content.dir/build.make CMakeFiles/rhea-content.dir/rel-ref.cpp.s
.PHONY : rel-ref.cpp.s

rel.o: rel.cpp.o

.PHONY : rel.o

# target to build an object file
rel.cpp.o:
	$(MAKE) -f CMakeFiles/rhea-rel.dir/build.make CMakeFiles/rhea-rel.dir/rel.cpp.o
.PHONY : rel.cpp.o

rel.i: rel.cpp.i

.PHONY : rel.i

# target to preprocess a source file
rel.cpp.i:
	$(MAKE) -f CMakeFiles/rhea-rel.dir/build.make CMakeFiles/rhea-rel.dir/rel.cpp.i
.PHONY : rel.cpp.i

rel.s: rel.cpp.s

.PHONY : rel.s

# target to generate assembly for a file
rel.cpp.s:
	$(MAKE) -f CMakeFiles/rhea-rel.dir/build.make CMakeFiles/rhea-rel.dir/rel.cpp.s
.PHONY : rel.cpp.s

rel_main.o: rel_main.cpp.o

.PHONY : rel_main.o

# target to build an object file
rel_main.cpp.o:
	$(MAKE) -f CMakeFiles/rhea-rel.dir/build.make CMakeFiles/rhea-rel.dir/rel_main.cpp.o
.PHONY : rel_main.cpp.o

rel_main.i: rel_main.cpp.i

.PHONY : rel_main.i

# target to preprocess a source file
rel_main.cpp.i:
	$(MAKE) -f CMakeFiles/rhea-rel.dir/build.make CMakeFiles/rhea-rel.dir/rel_main.cpp.i
.PHONY : rel_main.cpp.i

rel_main.s: rel_main.cpp.s

.PHONY : rel_main.s

# target to generate assembly for a file
rel_main.cpp.s:
	$(MAKE) -f CMakeFiles/rhea-rel.dir/build.make CMakeFiles/rhea-rel.dir/rel_main.cpp.s
.PHONY : rel_main.cpp.s

svisitor2met.o: svisitor2met.cpp.o

.PHONY : svisitor2met.o

# target to build an object file
svisitor2met.cpp.o:
	$(MAKE) -f CMakeFiles/rhea-diary.dir/build.make CMakeFiles/rhea-diary.dir/svisitor2met.cpp.o
.PHONY : svisitor2met.cpp.o

svisitor2met.i: svisitor2met.cpp.i

.PHONY : svisitor2met.i

# target to preprocess a source file
svisitor2met.cpp.i:
	$(MAKE) -f CMakeFiles/rhea-diary.dir/build.make CMakeFiles/rhea-diary.dir/svisitor2met.cpp.i
.PHONY : svisitor2met.cpp.i

svisitor2met.s: svisitor2met.cpp.s

.PHONY : svisitor2met.s

# target to generate assembly for a file
svisitor2met.cpp.s:
	$(MAKE) -f CMakeFiles/rhea-diary.dir/build.make CMakeFiles/rhea-diary.dir/svisitor2met.cpp.s
.PHONY : svisitor2met.cpp.s

svisitor4gxml.o: svisitor4gxml.cpp.o

.PHONY : svisitor4gxml.o

# target to build an object file
svisitor4gxml.cpp.o:
	$(MAKE) -f CMakeFiles/metis2xml.dir/build.make CMakeFiles/metis2xml.dir/svisitor4gxml.cpp.o
	$(MAKE) -f CMakeFiles/rhea-rel.dir/build.make CMakeFiles/rhea-rel.dir/svisitor4gxml.cpp.o
.PHONY : svisitor4gxml.cpp.o

svisitor4gxml.i: svisitor4gxml.cpp.i

.PHONY : svisitor4gxml.i

# target to preprocess a source file
svisitor4gxml.cpp.i:
	$(MAKE) -f CMakeFiles/metis2xml.dir/build.make CMakeFiles/metis2xml.dir/svisitor4gxml.cpp.i
	$(MAKE) -f CMakeFiles/rhea-rel.dir/build.make CMakeFiles/rhea-rel.dir/svisitor4gxml.cpp.i
.PHONY : svisitor4gxml.cpp.i

svisitor4gxml.s: svisitor4gxml.cpp.s

.PHONY : svisitor4gxml.s

# target to generate assembly for a file
svisitor4gxml.cpp.s:
	$(MAKE) -f CMakeFiles/metis2xml.dir/build.make CMakeFiles/metis2xml.dir/svisitor4gxml.cpp.s
	$(MAKE) -f CMakeFiles/rhea-rel.dir/build.make CMakeFiles/rhea-rel.dir/svisitor4gxml.cpp.s
.PHONY : svisitor4gxml.cpp.s

svisitor4rexml.o: svisitor4rexml.cpp.o

.PHONY : svisitor4rexml.o

# target to build an object file
svisitor4rexml.cpp.o:
	$(MAKE) -f CMakeFiles/metis2xml.dir/build.make CMakeFiles/metis2xml.dir/svisitor4rexml.cpp.o
.PHONY : svisitor4rexml.cpp.o

svisitor4rexml.i: svisitor4rexml.cpp.i

.PHONY : svisitor4rexml.i

# target to preprocess a source file
svisitor4rexml.cpp.i:
	$(MAKE) -f CMakeFiles/metis2xml.dir/build.make CMakeFiles/metis2xml.dir/svisitor4rexml.cpp.i
.PHONY : svisitor4rexml.cpp.i

svisitor4rexml.s: svisitor4rexml.cpp.s

.PHONY : svisitor4rexml.s

# target to generate assembly for a file
svisitor4rexml.cpp.s:
	$(MAKE) -f CMakeFiles/metis2xml.dir/build.make CMakeFiles/metis2xml.dir/svisitor4rexml.cpp.s
.PHONY : svisitor4rexml.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... rhea-diary"
	@echo "... edit_cache"
	@echo "... list_install_components"
	@echo "... metis2xml"
	@echo "... rebuild_cache"
	@echo "... rhea-rel"
	@echo "... rhea-content"
	@echo "... diary.o"
	@echo "... diary.i"
	@echo "... diary.s"
	@echo "... diary_main.o"
	@echo "... diary_main.i"
	@echo "... diary_main.s"
	@echo "... m2x_main.o"
	@echo "... m2x_main.i"
	@echo "... m2x_main.s"
	@echo "... metis2xml.o"
	@echo "... metis2xml.i"
	@echo "... metis2xml.s"
	@echo "... refer.o"
	@echo "... refer.i"
	@echo "... refer.s"
	@echo "... rel-ref.o"
	@echo "... rel-ref.i"
	@echo "... rel-ref.s"
	@echo "... rel.o"
	@echo "... rel.i"
	@echo "... rel.s"
	@echo "... rel_main.o"
	@echo "... rel_main.i"
	@echo "... rel_main.s"
	@echo "... svisitor2met.o"
	@echo "... svisitor2met.i"
	@echo "... svisitor2met.s"
	@echo "... svisitor4gxml.o"
	@echo "... svisitor4gxml.i"
	@echo "... svisitor4gxml.s"
	@echo "... svisitor4rexml.o"
	@echo "... svisitor4rexml.i"
	@echo "... svisitor4rexml.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

